name: Build local assets
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: build dist
        run: |
          echo ${{ github.event.inputs.TAG }}
          npm install -g @angular/cli
          npm i
          echo start build
          git rm -rf static/web/*
          ng build --configuration production
          ls static/web
      - name: commit 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: '-u'
          push_options: '--force'
          skip_fetch: true 
          commit_message: ":bookmark: Release elernal-tree commit tag ${{ github.event.inputs.TAG }}"
          file_pattern: static/web/*
      - name: update repo
        run: |
          git pull
          ls static/web/*
      - uses: actions/checkout@v2
      - name: Release to github
        uses: ncipollo/release-action@v1
        with:
            allowUpdates: true
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.event.inputs.TAG }}